---

esphome:
  name: utemp
  name_add_mac_suffix: true
  friendly_name: "µtemp Sensor"
  project:
    name: "Joshua Boniface.µtemp"
    version: "1.1"

dashboard_import:
  package_import_url: github://joshuaboniface/supersensor/utemp.yaml

esp8266:
  board: esp01_1m
  restore_from_flash: true

preferences:
  flash_write_interval: 15sec

globals:
  - id: temperature_offset
    type: float
    restore_value: true
    initial_value: "0.0"

logger:
  level: INFO
  baud_rate: 0

api:
  reboot_timeout: 15min

ota:
  platform: esphome

web_server:
  port: 80

captive_portal:

mdns:
  disabled: false

wifi:
  ap: {}
  domain: ""
  output_power: 8.5dB
  reboot_timeout: 15min
  power_save_mode: none

i2c:
  - id: i2c_bus
    sda: GPIO5
    scl: GPIO4
    scan: true

sensor:
  - platform: sgp30
    eco2:
      name: "eCO2"
      accuracy_decimals: 1
    tvoc:
      name: "TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 15s

  - platform: bmp280_i2c
    temperature:
      name: "Temperature"
      oversampling: 16x
      filters:
        - offset: !lambda return id(temperature_offset);
    pressure:
      name: "Pressure"
    address: 0x76
    update_interval: 15s

number:
  # Temperature offset:
  # A calibration from -7 to +3 for the temperature sensor of the BMP280
  - platform: template
    name: "Temperature Offset"
    id: temperature_offset_setter
    min_value: -7
    max_value: 3
    step: 0.1
    lambda: |-
      return id(temperature_offset);
    set_action:
      then:
        - globals.set:
            id: temperature_offset
            value: !lambda 'return float(x);'

