---

###############################################################################
# SuperSensor v1.0 ESPHome configuration
###############################################################################
#
#    Copyright (C) 2023 Joshua M. Boniface <joshua@boniface.me>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################

esphome:
  name: pirtester
  friendly_name: "PIRTester"

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "240"
      CONFIG_ESP32_DATA_CACHE_64KB: "y"
      CONFIG_ESP32_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ: "240"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"

# Enable logging only via web
logger:
  level: DEBUG
  baud_rate: 115200

api:
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password
  safe_mode: false

web_server:
  port: 80
  auth:
    username: !secret web_auth_username
    password: !secret web_auth_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain
  power_save_mode: LIGHT
  reboot_timeout: 5min

binary_sensor:
  - platform: gpio
    pin: GPIO32
    name: "PIR 32"
    device_class: motion
  - platform: gpio
    pin: GPIO33
    name: "PIR 33"
    device_class: motion
  - platform: gpio
    pin: GPIO25
    name: "PIR 25"
    device_class: motion
  - platform: gpio
    pin: GPIO26
    name: "PIR 26"
    device_class: motion
  - platform: gpio
    pin: GPIO27
    name: "PIR 27"
    device_class: motion
  - platform: gpio
    pin: GPIO14
    name: "PIR 14"
    device_class: motion
  - platform: gpio
    pin: GPIO12
    name: "PIR 12"
    device_class: motion
  - platform: gpio
    pin: GPIO13
    name: "PIR 13"
    device_class: motion
